// M0-07: RBAC 权限点常量（唯一真相源） | HRMS | 2026-08-24
// seed.ts 与后端中间件统一引用本文件，禁止在别处重复硬编码权限数组

/** 通配权限：拥有全部权限 */
export const WILDCARD = '*';

/**
 * 系统全部权限点
 */
export const PERMISSIONS = {
  // 组织人事
  EMPLOYEE_READ: 'employee:read',
  EMPLOYEE_WRITE: 'employee:write',
  EMPLOYEE_READ_SELF_DEPT: 'employee:read:self-dept',
  DEPARTMENT_READ: 'department:read',
  DEPARTMENT_WRITE: 'department:write',

  // 考勤
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_WRITE: 'attendance:write',
  ATTENDANCE_READ_SELF_DEPT: 'attendance:read:self-dept',
  ATTENDANCE_READ_SELF: 'attendance:read:self',
  ATTENDANCE_WRITE_SELF: 'attendance:write:self',
  ATTENDANCE_APPROVE: 'attendance:approve',

  // 薪酬
  SALARY_READ: 'salary:read',
  SALARY_WRITE: 'salary:write',
  SALARY_READ_SELF: 'salary:read:self',
  SALARY_APPROVE: 'salary:approve',

  // 绩效
  PERFORMANCE_READ: 'performance:read',
  PERFORMANCE_WRITE: 'performance:write',
  PERFORMANCE_READ_SELF_DEPT: 'performance:read:self-dept',
  PERFORMANCE_WRITE_SELF_DEPT: 'performance:write:self-dept',
  PERFORMANCE_READ_SELF: 'performance:read:self',
  PERFORMANCE_WRITE_SELF: 'performance:write:self',
  PERFORMANCE_APPROVE: 'performance:approve',

  // 合同
  CONTRACT_READ: 'contract:read',
  CONTRACT_WRITE: 'contract:write',

  // 假勤
  LEAVE_APPLY: 'leave:apply',
  LEAVE_APPROVE: 'leave:approve',
  OVERTIME_APPLY: 'overtime:apply',
  OVERTIME_APPROVE: 'overtime:approve',

  // 报表
  REPORT_READ: 'report:read',

  // 个人中心
  PROFILE_READ_SELF: 'profile:read:self',
  PROFILE_WRITE_SELF: 'profile:write:self',

  // 审计日志（M0-08）
  AUDIT_READ: 'audit:read',

  // —— 以下为 M0.5 权限点（审计收敛后新增）——
  APPROVAL_FLOW_READ: 'approval:flow:read',
  APPROVAL_FLOW_WRITE: 'approval:flow:write',
  APPROVAL_INSTANCE_ACT: 'approval:instance:act',
  NOTIFICATION_SEND: 'notification:send',
  NOTIFICATION_TEMPLATE_READ: 'notification:template:read',
  NOTIFICATION_TEMPLATE_WRITE: 'notification:template:write',
  ENCRYPTED_FIELD_READ: 'encrypted-field:read',
  ENCRYPTED_FIELD_WRITE: 'encrypted-field:write',
  ENCRYPTED_FIELD_DECRYPT: 'encrypted-field:decrypt',
  ENCRYPTED_FIELD_ROTATE: 'encrypted-field:rotate',
  INTEGRATION_READ: 'integration:read',
  INTEGRATION_WRITE: 'integration:write',
  INTEGRATION_SEND: 'integration:send',
  CONFIG_READ: 'config:read',
  CONFIG_WRITE: 'config:write',

  // AI 底座（M0.5-5）
  AI_OCR: 'ai:ocr',
  AI_QA: 'ai:qa',
  AI_SUMMARIZE: 'ai:summarize',
  AI_SCORE: 'ai:score',
  AI_DOCUMENT_READ: 'ai:document:read',
  AI_DOCUMENT_WRITE: 'ai:document:write',
  AI_CONVERSATION_READ: 'ai:conversation:read',
} as const;

/** 权限点字面量联合类型 */
export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * 角色 code → 权限点数组 映射
 * admin 为 ['*'] 通配
 */
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [WILDCARD],
  hr: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_WRITE,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.SALARY_READ,
    PERMISSIONS.SALARY_WRITE,
    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PERFORMANCE_WRITE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_WRITE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.APPROVAL_FLOW_READ,
    PERMISSIONS.APPROVAL_FLOW_WRITE,
    PERMISSIONS.APPROVAL_INSTANCE_ACT,
    PERMISSIONS.NOTIFICATION_SEND,
    PERMISSIONS.NOTIFICATION_TEMPLATE_READ,
    PERMISSIONS.NOTIFICATION_TEMPLATE_WRITE,
    PERMISSIONS.ENCRYPTED_FIELD_READ,
    PERMISSIONS.ENCRYPTED_FIELD_DECRYPT,
    PERMISSIONS.INTEGRATION_READ,
    PERMISSIONS.CONFIG_READ,
    PERMISSIONS.CONFIG_WRITE,
    PERMISSIONS.AI_OCR,
    PERMISSIONS.AI_QA,
    PERMISSIONS.AI_SUMMARIZE,
    PERMISSIONS.AI_SCORE,
    PERMISSIONS.AI_DOCUMENT_READ,
    PERMISSIONS.AI_DOCUMENT_WRITE,
    PERMISSIONS.AI_CONVERSATION_READ,
  ],
  dept_head: [
    PERMISSIONS.EMPLOYEE_READ_SELF_DEPT,
    PERMISSIONS.ATTENDANCE_READ_SELF_DEPT,
    PERMISSIONS.ATTENDANCE_APPROVE,
    PERMISSIONS.PERFORMANCE_READ_SELF_DEPT,
    PERMISSIONS.PERFORMANCE_WRITE_SELF_DEPT,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.OVERTIME_APPROVE,
    PERMISSIONS.APPROVAL_INSTANCE_ACT,
  ],
  executive: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.SALARY_READ,
    PERMISSIONS.SALARY_APPROVE,
    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PERFORMANCE_APPROVE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.APPROVAL_INSTANCE_ACT,
    PERMISSIONS.CONFIG_READ,
  ],
  employee: [
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_WRITE_SELF,
    PERMISSIONS.ATTENDANCE_READ_SELF,
    PERMISSIONS.ATTENDANCE_WRITE_SELF,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.OVERTIME_APPLY,
    PERMISSIONS.SALARY_READ_SELF,
    PERMISSIONS.PERFORMANCE_READ_SELF,
    PERMISSIONS.PERFORMANCE_WRITE_SELF,
    PERMISSIONS.APPROVAL_INSTANCE_ACT,
    PERMISSIONS.AI_OCR,
    PERMISSIONS.AI_QA,
    PERMISSIONS.AI_SUMMARIZE,
    PERMISSIONS.AI_SCORE,
    PERMISSIONS.AI_DOCUMENT_READ,
    PERMISSIONS.AI_CONVERSATION_READ,
  ],
};
