// M0-07: RBAC 权限点常量（唯一真相源） | HRMS | 2026-08-24
// seed.ts 与后端中间件统一引用本文件，禁止在别处重复硬编码权限数组

/** 通配权限：拥有全部权限 */
export const WILDCARD = '*';

/**
 * 系统全部权限点
 */
export const PERMISSIONS = {
  // 组织人事
  EMPLOYEE_READ: 'employee:read',
  EMPLOYEE_WRITE: 'employee:write',
  EMPLOYEE_READ_SELF_DEPT: 'employee:read:self-dept',
  DEPARTMENT_READ: 'department:read',
  DEPARTMENT_WRITE: 'department:write',

  // 考勤
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_WRITE: 'attendance:write',
  ATTENDANCE_READ_SELF_DEPT: 'attendance:read:self-dept',
  ATTENDANCE_READ_SELF: 'attendance:read:self',
  ATTENDANCE_WRITE_SELF: 'attendance:write:self',
  ATTENDANCE_APPROVE: 'attendance:approve',

  // 薪酬
  SALARY_READ: 'salary:read',
  SALARY_WRITE: 'salary:write',
  SALARY_READ_SELF: 'salary:read:self',
  SALARY_APPROVE: 'salary:approve',
  // M4-C1 薪级薪档 + 薪酬方案
  SALARY_GRADE_READ: 'salary:grade:read',
  SALARY_GRADE_WRITE: 'salary:grade:write',
  SALARY_PLAN_READ: 'salary:plan:read',
  SALARY_PLAN_WRITE: 'salary:plan:write',

  // 绩效
  PERFORMANCE_READ: 'performance:read',
  PERFORMANCE_WRITE: 'performance:write',
  PERFORMANCE_READ_SELF_DEPT: 'performance:read:self-dept',
  PERFORMANCE_WRITE_SELF_DEPT: 'performance:write:self-dept',
  PERFORMANCE_READ_SELF: 'performance:read:self',
  PERFORMANCE_WRITE_SELF: 'performance:write:self',
  PERFORMANCE_APPROVE: 'performance:approve',

  // 合同
  CONTRACT_READ: 'contract:read',
  CONTRACT_WRITE: 'contract:write',

  // 假勤
  LEAVE_APPLY: 'leave:apply',
  LEAVE_APPROVE: 'leave:approve',
  OVERTIME_APPLY: 'overtime:apply',
  OVERTIME_APPROVE: 'overtime:approve',

  // 报表
  REPORT_READ: 'report:read',

  // 个人中心
  PROFILE_READ_SELF: 'profile:read:self',
  PROFILE_WRITE_SELF: 'profile:write:self',

  // 审计日志（M0-08）
  AUDIT_READ: 'audit:read',

  // —— 以下为 M0.5 权限点（审计收敛后新增）——
  APPROVAL_FLOW_READ: 'approval:flow:read',
  APPROVAL_FLOW_WRITE: 'approval:flow:write',
  APPROVAL_INSTANCE_ACT: 'approval:instance:act',
  NOTIFICATION_SEND: 'notification:send',
  NOTIFICATION_TEMPLATE_READ: 'notification:template:read',
  NOTIFICATION_TEMPLATE_WRITE: 'notification:template:write',
  ENCRYPTED_FIELD_READ: 'encrypted-field:read',
  ENCRYPTED_FIELD_WRITE: 'encrypted-field:write',
  ENCRYPTED_FIELD_DECRYPT: 'encrypted-field:decrypt',
  ENCRYPTED_FIELD_ROTATE: 'encrypted-field:rotate',
  INTEGRATION_READ: 'integration:read',
  INTEGRATION_WRITE: 'integration:write',
  INTEGRATION_SEND: 'integration:send',
  CONFIG_READ: 'config:read',
  CONFIG_WRITE: 'config:write',

  // AI 底座（M0.5-5）
  AI_OCR: 'ai:ocr',
  AI_QA: 'ai:qa',
  AI_SUMMARIZE: 'ai:summarize',
  AI_SCORE: 'ai:score',
  AI_DOCUMENT_READ: 'ai:document:read',
  AI_DOCUMENT_WRITE: 'ai:document:write',
  AI_CONVERSATION_READ: 'ai:conversation:read',

  // M1-A1 组织架构
  COMPANY_READ: 'company:read',
  COMPANY_WRITE: 'company:write',
  // M1-A2 员工档案（DEPARTMENT_* / EMPLOYEE_READ/WRITE 已存在，复用）
  EMPLOYEE_READ_SENSITIVE: 'employee:read_sensitive',
  EMPLOYEE_AI_OCR: 'employee:ai_ocr',

  // M1-A3 入职流程
  ONBOARDING_READ: 'onboarding:read',
  ONBOARDING_WRITE: 'onboarding:write',
  ONBOARDING_CONFIRM: 'onboarding:confirm',

  // M1-A4 转正流程
  REGULARIZATION_READ: 'regularization:read',
  REGULARIZATION_WRITE: 'regularization:write',

  // M1-A6 离职流程
  OFFBOARDING_READ: 'offboarding:read',
  OFFBOARDING_WRITE: 'offboarding:write',
  OFFBOARDING_CERTIFICATE: 'offboarding:certificate',

  // M1-A5 调动流程
  TRANSFER_READ: 'transfer:read',
  TRANSFER_WRITE: 'transfer:write',
  TRANSFER_APPROVE: 'transfer:approve',

  // M1-A7 合同管理
  CONTRACT_SIGN: 'contract:sign',

  // M2-B1 班次定义
  SHIFT_READ: 'shift:read',
  SHIFT_WRITE: 'shift:write',
  SHIFT_ASSIGN: 'shift:assign',

  // M2-B2 打卡管理
  ATTENDANCE_CLOCK: 'attendance:clock',
  ATTENDANCE_MANUAL: 'attendance:manual',

  // M2-B3 请假
  LEAVE_READ: 'leave:read',
  LEAVE_REQUEST: 'leave:request',
  LEAVE_CANCEL: 'leave:cancel',

  // M2-B4 加班
  OVERTIME_READ: 'overtime:read',
  OVERTIME_REQUEST: 'overtime:request',
  OVERTIME_CANCEL: 'overtime:cancel',

  // M2-B5 出差
  TRIP_READ: 'trip:read',
  TRIP_REQUEST: 'trip:request',
  TRIP_CANCEL: 'trip:cancel',

  // M2-B6 月度考勤汇总
  SUMMARY_READ: 'summary:read',
  SUMMARY_LOCK: 'summary:lock',

  // M3-D1 考核方案配置
  PERFORMANCE_CYCLE_READ: 'performance:cycle:read',
  PERFORMANCE_CYCLE_WRITE: 'performance:cycle:write',
  PERFORMANCE_INDICATOR_READ: 'performance:indicator:read',
  PERFORMANCE_INDICATOR_WRITE: 'performance:indicator:write',
  PERFORMANCE_SCHEME_READ: 'performance:scheme:read',
  PERFORMANCE_SCHEME_WRITE: 'performance:scheme:write',
  PERFORMANCE_COEFFICIENT_READ: 'performance:coefficient:read',
  PERFORMANCE_COEFFICIENT_WRITE: 'performance:coefficient:write',

  // M3-D2 考核流程
  PERFORMANCE_RECORD_READ: 'performance:record:read',
  PERFORMANCE_RECORD_WRITE: 'performance:record:write',
  PERFORMANCE_SELF_SUBMIT: 'performance:self:submit',
  PERFORMANCE_MANAGER_SCORE: 'performance:manager:score',
  PERFORMANCE_DEPT_CALIBRATE: 'performance:dept:calibrate',
  PERFORMANCE_HR_SUMMARY: 'performance:hr:summary',
  PERFORMANCE_CEO_APPROVE: 'performance:ceo:approve',
  PERFORMANCE_AI_REQUEST: 'performance:ai:request',
  PERFORMANCE_AI_READ: 'performance:ai:read',

  // M3-D3 五档评分 + 系数配置
  PERFORMANCE_GRADE_CALCULATE: 'performance:grade:calculate',
  PERFORMANCE_GRADE_THRESHOLD_READ: 'performance:grade:threshold:read',
  PERFORMANCE_GRADE_THRESHOLD_WRITE: 'performance:grade:threshold:write',

  // M3-D4 绩效兑现
  PERFORMANCE_PAYOUT_READ: 'performance:payout:read',
  PERFORMANCE_PAYOUT_WRITE: 'performance:payout:write',
  PERFORMANCE_PAYOUT_CALCULATE: 'performance:payout:calculate',
  PERFORMANCE_PAYOUT_SETTLE: 'performance:payout:settle',

  // M3-D5 销售提成
  PERFORMANCE_SALES_PRODUCT_READ: 'performance:sales:product:read',
  PERFORMANCE_SALES_PRODUCT_WRITE: 'performance:sales:product:write',
  PERFORMANCE_SALES_PAYMENT_READ: 'performance:sales:payment:read',
  PERFORMANCE_SALES_PAYMENT_WRITE: 'performance:sales:payment:write',
  PERFORMANCE_SALES_PAYMENT_CONFIRM: 'performance:sales:payment:confirm',
  PERFORMANCE_SALES_COMMISSION_READ: 'performance:sales:commission:read',
  PERFORMANCE_SALES_COMMISSION_WRITE: 'performance:sales:commission:write',

  // M3-D6 结果应用
  PERFORMANCE_SALARY_ADJUSTMENT_READ: 'performance:salary-adjustment:read',
  PERFORMANCE_SALARY_ADJUSTMENT_WRITE: 'performance:salary-adjustment:write',
  PERFORMANCE_SALARY_ADJUSTMENT_APPROVE: 'performance:salary-adjustment:approve',
  PERFORMANCE_PROMOTION_READ: 'performance:promotion:read',
  PERFORMANCE_PROMOTION_WRITE: 'performance:promotion:write',
  PERFORMANCE_PIP_READ: 'performance:pip:read',
  PERFORMANCE_PIP_WRITE: 'performance:pip:write',
  PERFORMANCE_PIP_REVIEW: 'performance:pip:review',
} as const;

/** 权限点字面量联合类型 */
export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * 角色 code → 权限点数组 映射
 * admin 为 ['*'] 通配
 */
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [WILDCARD],
  hr: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_WRITE,
    PERMISSIONS.EMPLOYEE_READ_SENSITIVE,
    PERMISSIONS.EMPLOYEE_AI_OCR,
    PERMISSIONS.COMPANY_READ,
    PERMISSIONS.COMPANY_WRITE,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.SALARY_READ,
    PERMISSIONS.SALARY_WRITE,
    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PERFORMANCE_WRITE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_WRITE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.APPROVAL_FLOW_READ,
    PERMISSIONS.APPROVAL_FLOW_WRITE,
    PERMISSIONS.APPROVAL_INSTANCE_ACT,
    PERMISSIONS.NOTIFICATION_SEND,
    PERMISSIONS.NOTIFICATION_TEMPLATE_READ,
    PERMISSIONS.NOTIFICATION_TEMPLATE_WRITE,
    PERMISSIONS.ENCRYPTED_FIELD_READ,
    PERMISSIONS.ENCRYPTED_FIELD_DECRYPT,
    PERMISSIONS.INTEGRATION_READ,
    PERMISSIONS.CONFIG_READ,
    PERMISSIONS.CONFIG_WRITE,
    PERMISSIONS.AI_OCR,
    PERMISSIONS.AI_QA,
    PERMISSIONS.AI_SUMMARIZE,
    PERMISSIONS.AI_SCORE,
    PERMISSIONS.AI_DOCUMENT_READ,
    PERMISSIONS.AI_DOCUMENT_WRITE,
    PERMISSIONS.AI_CONVERSATION_READ,
    PERMISSIONS.ONBOARDING_READ,
    PERMISSIONS.ONBOARDING_WRITE,
    PERMISSIONS.ONBOARDING_CONFIRM,
    PERMISSIONS.REGULARIZATION_READ,
    PERMISSIONS.REGULARIZATION_WRITE,
    PERMISSIONS.OFFBOARDING_READ,
    PERMISSIONS.OFFBOARDING_WRITE,
    PERMISSIONS.OFFBOARDING_CERTIFICATE,
    PERMISSIONS.TRANSFER_READ,
    PERMISSIONS.TRANSFER_WRITE,
    PERMISSIONS.TRANSFER_APPROVE,
    PERMISSIONS.CONTRACT_SIGN,
    PERMISSIONS.SHIFT_READ,
    PERMISSIONS.SHIFT_WRITE,
    PERMISSIONS.SHIFT_ASSIGN,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.ATTENDANCE_MANUAL,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.OVERTIME_READ,
    PERMISSIONS.OVERTIME_REQUEST,
    PERMISSIONS.OVERTIME_CANCEL,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.TRIP_REQUEST,
    PERMISSIONS.TRIP_CANCEL,
    PERMISSIONS.SUMMARY_READ,
    PERMISSIONS.SUMMARY_LOCK,
    PERMISSIONS.PERFORMANCE_CYCLE_READ,
    PERMISSIONS.PERFORMANCE_CYCLE_WRITE,
    PERMISSIONS.PERFORMANCE_INDICATOR_READ,
    PERMISSIONS.PERFORMANCE_INDICATOR_WRITE,
    PERMISSIONS.PERFORMANCE_SCHEME_READ,
    PERMISSIONS.PERFORMANCE_SCHEME_WRITE,
    PERMISSIONS.PERFORMANCE_COEFFICIENT_READ,
    PERMISSIONS.PERFORMANCE_COEFFICIENT_WRITE,
    PERMISSIONS.PERFORMANCE_RECORD_READ,
    PERMISSIONS.PERFORMANCE_RECORD_WRITE,
    PERMISSIONS.PERFORMANCE_HR_SUMMARY,
    PERMISSIONS.PERFORMANCE_AI_READ,
    PERMISSIONS.PERFORMANCE_GRADE_CALCULATE,
    PERMISSIONS.PERFORMANCE_GRADE_THRESHOLD_READ,
    PERMISSIONS.PERFORMANCE_GRADE_THRESHOLD_WRITE,
    PERMISSIONS.PERFORMANCE_PAYOUT_READ,
    PERMISSIONS.PERFORMANCE_PAYOUT_WRITE,
    PERMISSIONS.PERFORMANCE_PAYOUT_CALCULATE,
    PERMISSIONS.PERFORMANCE_PAYOUT_SETTLE,
    PERMISSIONS.PERFORMANCE_SALES_PRODUCT_READ,
    PERMISSIONS.PERFORMANCE_SALES_PRODUCT_WRITE,
    PERMISSIONS.PERFORMANCE_SALES_PAYMENT_READ,
    PERMISSIONS.PERFORMANCE_SALES_PAYMENT_WRITE,
    PERMISSIONS.PERFORMANCE_SALES_PAYMENT_CONFIRM,
    PERMISSIONS.PERFORMANCE_SALES_COMMISSION_READ,
    PERMISSIONS.PERFORMANCE_SALES_COMMISSION_WRITE,
    PERMISSIONS.PERFORMANCE_SALARY_ADJUSTMENT_READ,
    PERMISSIONS.PERFORMANCE_SALARY_ADJUSTMENT_WRITE,
    PERMISSIONS.PERFORMANCE_PROMOTION_READ,
    PERMISSIONS.PERFORMANCE_PROMOTION_WRITE,
    PERMISSIONS.PERFORMANCE_PIP_READ,
    PERMISSIONS.PERFORMANCE_PIP_WRITE,
    PERMISSIONS.PERFORMANCE_PIP_REVIEW,
    PERMISSIONS.SALARY_GRADE_READ,
    PERMISSIONS.SALARY_GRADE_WRITE,
    PERMISSIONS.SALARY_PLAN_READ,
    PERMISSIONS.SALARY_PLAN_WRITE,
  ],
  dept_head: [
    PERMISSIONS.EMPLOYEE_READ_SELF_DEPT,
    PERMISSIONS.ATTENDANCE_READ_SELF_DEPT,
    PERMISSIONS.ATTENDANCE_APPROVE,
    PERMISSIONS.PERFORMANCE_READ_SELF_DEPT,
    PERMISSIONS.PERFORMANCE_WRITE_SELF_DEPT,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.OVERTIME_APPROVE,
    PERMISSIONS.APPROVAL_INSTANCE_ACT,
    PERMISSIONS.ONBOARDING_READ,
    PERMISSIONS.REGULARIZATION_READ,
    PERMISSIONS.OFFBOARDING_READ,
    PERMISSIONS.TRANSFER_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.SHIFT_READ,
    PERMISSIONS.SHIFT_ASSIGN,
    PERMISSIONS.ATTENDANCE_MANUAL,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.OVERTIME_READ,
    PERMISSIONS.OVERTIME_CANCEL,
    PERMISSIONS.TRIP_READ,
    PERMISSIONS.TRIP_CANCEL,
    PERMISSIONS.SUMMARY_READ,
    PERMISSIONS.PERFORMANCE_CYCLE_READ,
    PERMISSIONS.PERFORMANCE_INDICATOR_READ,
    PERMISSIONS.PERFORMANCE_SCHEME_READ,
    PERMISSIONS.PERFORMANCE_COEFFICIENT_READ,
    PERMISSIONS.PERFORMANCE_RECORD_READ,
    PERMISSIONS.PERFORMANCE_MANAGER_SCORE,
    PERMISSIONS.PERFORMANCE_DEPT_CALIBRATE,
    PERMISSIONS.PERFORMANCE_AI_REQUEST,
    PERMISSIONS.PERFORMANCE_AI_READ,
    PERMISSIONS.PERFORMANCE_PAYOUT_READ,
    PERMISSIONS.PERFORMANCE_SALES_PRODUCT_READ,
    PERMISSIONS.PERFORMANCE_SALES_PAYMENT_READ,
    PERMISSIONS.PERFORMANCE_SALES_COMMISSION_READ,
    PERMISSIONS.PERFORMANCE_SALARY_ADJUSTMENT_READ,
    PERMISSIONS.PERFORMANCE_PROMOTION_READ,
    PERMISSIONS.PERFORMANCE_PIP_READ,
    PERMISSIONS.SALARY_GRADE_READ,
    PERMISSIONS.SALARY_PLAN_READ,
  ],
  executive: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.SALARY_READ,
    PERMISSIONS.SALARY_APPROVE,
    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PERFORMANCE_APPROVE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.APPROVAL_INSTANCE_ACT,
    PERMISSIONS.CONFIG_READ,
    PERMISSIONS.TRANSFER_READ,
    PERMISSIONS.TRANSFER_APPROVE,
    PERMISSIONS.PERFORMANCE_CYCLE_READ,
    PERMISSIONS.PERFORMANCE_INDICATOR_READ,
    PERMISSIONS.PERFORMANCE_SCHEME_READ,
    PERMISSIONS.PERFORMANCE_COEFFICIENT_READ,
    PERMISSIONS.PERFORMANCE_COEFFICIENT_WRITE,
    PERMISSIONS.PERFORMANCE_RECORD_READ,
    PERMISSIONS.PERFORMANCE_CEO_APPROVE,
    PERMISSIONS.PERFORMANCE_AI_REQUEST,
    PERMISSIONS.PERFORMANCE_AI_READ,
    PERMISSIONS.PERFORMANCE_GRADE_CALCULATE,
    PERMISSIONS.PERFORMANCE_GRADE_THRESHOLD_READ,
    PERMISSIONS.PERFORMANCE_PAYOUT_READ,
    PERMISSIONS.PERFORMANCE_PAYOUT_CALCULATE,
    PERMISSIONS.PERFORMANCE_PAYOUT_SETTLE,
    PERMISSIONS.PERFORMANCE_SALES_PRODUCT_READ,
    PERMISSIONS.PERFORMANCE_SALES_PAYMENT_READ,
    PERMISSIONS.PERFORMANCE_SALES_COMMISSION_READ,
    PERMISSIONS.PERFORMANCE_SALES_COMMISSION_WRITE,
    PERMISSIONS.PERFORMANCE_SALARY_ADJUSTMENT_READ,
    PERMISSIONS.PERFORMANCE_SALARY_ADJUSTMENT_APPROVE,
    PERMISSIONS.PERFORMANCE_PROMOTION_READ,
    PERMISSIONS.PERFORMANCE_PIP_READ,
    PERMISSIONS.PERFORMANCE_PIP_REVIEW,
    PERMISSIONS.SALARY_GRADE_READ,
    PERMISSIONS.SALARY_PLAN_READ,
  ],
  employee: [
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_WRITE_SELF,
    PERMISSIONS.ATTENDANCE_READ_SELF,
    PERMISSIONS.ATTENDANCE_WRITE_SELF,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_REQUEST,
    PERMISSIONS.OVERTIME_APPLY,
    PERMISSIONS.OVERTIME_REQUEST,
    PERMISSIONS.TRIP_REQUEST,
    PERMISSIONS.SUMMARY_READ,
    PERMISSIONS.SALARY_READ_SELF,
    PERMISSIONS.PERFORMANCE_READ_SELF,
    PERMISSIONS.PERFORMANCE_WRITE_SELF,
    PERMISSIONS.APPROVAL_INSTANCE_ACT,
    PERMISSIONS.AI_OCR,
    PERMISSIONS.AI_QA,
    PERMISSIONS.AI_SUMMARIZE,
    PERMISSIONS.AI_SCORE,
    PERMISSIONS.AI_DOCUMENT_READ,
    PERMISSIONS.AI_CONVERSATION_READ,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.PERFORMANCE_RECORD_READ,
    PERMISSIONS.PERFORMANCE_SELF_SUBMIT,
    PERMISSIONS.PERFORMANCE_PAYOUT_READ,
    PERMISSIONS.PERFORMANCE_SALES_PRODUCT_READ,
    PERMISSIONS.PERFORMANCE_SALARY_ADJUSTMENT_READ,
    PERMISSIONS.PERFORMANCE_PROMOTION_READ,
    PERMISSIONS.PERFORMANCE_PIP_READ,
    PERMISSIONS.SALARY_PLAN_READ,
  ],
};
