// M5-03: 员工数据迁移 | HRMS | 2026-09-02
// 用途：解析员工档案迁移模板 xlsx → 校验 → dry-run → 正式导入（复用 createEmployee）→ 幂等 → 报告
// 用法：
//   pnpm --filter hrms-server migration:employees -- --file output/员工档案迁移样例.xlsx --dry-run
//   pnpm --filter hrms-server migration:employees -- --file output/员工档案迁移样例.xlsx
//   pnpm --filter hrms-server migration:employees -- --file output/员工档案迁移样例.xlsx --purge-test-data
//
// 关键决策（见交付报告）：
//   1. 工号保留走「补偿式回滚」（createEmployee 内部无事务，含 BullMQ 调度，
//      不能也不应强行包外层 $transaction；失败时 hard-delete 回收）。
//   2. createEmployee 不接 employeeNo 入参；先 create 拿到自增工号，
//      再 prisma.employee.update 改回 Excel 工号；二者均失败时硬删整行（连同
//      employee_position_history + employee_salary_history，因为这两表无 FK）。

// M5-03: 员工数据迁移 | HRMS | 2026-09-02
// 用途：解析员工档案迁移模板 xlsx → 校验 → dry-run → 正式导入（复用 createEmployee）→ 幂等 → 报告
// 用法：
//   pnpm --filter hrms-server migration:employees -- --file output/员工档案迁移样例.xlsx --dry-run
//   pnpm --filter hrms-server migration:employees -- --file output/员工档案迁移样例.xlsx
//   pnpm --filter hrms-server migration:employees -- --file output/员工档案迁移样例.xlsx --purge-test-data
//
// 关键决策（见交付报告）：
//   1. 工号保留走「补偿式回滚」（createEmployee 内部无事务，含 BullMQ 调度，
//      不能也不应强行包外层 $transaction；失败时 hard-delete 回收）。
//   2. createEmployee 不接 employeeNo 入参；先 create 拿到自增工号，
//      再 prisma.employee.update 改回 Excel 工号；二者均失败时硬删整行（连同
//      employee_position_history + employee_salary_history，因为这两表无 FK）。
//   3. NODE_ENV 设为 test（动态 import 之前），关掉 src/lib/prisma.ts 的开发态 query 日志；
//      上线真实迁移时可手动 export NODE_ENV=development。

// ⚠️ 必须放在任何 src/ 导入之前：强制 test 模式，关掉 Prisma query 日志
process.env.NODE_ENV = process.env.NODE_ENV === 'production' ? 'production' : 'test';

import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import dotenv from 'dotenv';
import { PrismaClient, Prisma } from '@prisma/client';
import * as XLSX from 'xlsx';

dotenv.config();

// 动态 import：保证 NODE_ENV=test 在 src/services/employee.service 模块加载前生效
const employeeService = await import('../../src/services/employee.service');
const createEmployee = employeeService.createEmployee;
type CreateEmployeeInput = employeeService.CreateEmployeeInput;

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = path.join(SCRIPT_DIR, 'output');
const TEST_EMP_PREFIX = 'XACH2099';

const prisma = new PrismaClient({
  log: ['error'],
});

const REQUIRED_HEADERS = ['工号', '姓名', '部门代码', '入职日期'] as const;

const ENUM_MAPS = {
  gender: { 男: 'male', 女: 'female' },
  contractType: { 正式: 'formal', 实习: 'intern', 顾问: 'consultant', 劳务: 'labor' },
  status: { 试用期: 'probation', 在职: 'active' },
  socialInsured: { 是: true, 否: false },
} as const;

interface CliArgs {
  file: string | null;
  company: string;
  dryRun: boolean;
  purgeTestData: boolean;
}

interface CellError {
  field: string;
  reason: string;
}

interface RowResult {
  rowIndex: number; // Excel 数据行号（含表头，所以从 2 开始）
  employeeNo: string; // Excel 中期望的工号
  name: string;
  result: 'success' | 'skipped' | 'failed';
  reason?: string;
  errors?: CellError[];
  employeeId?: string;
  autoGeneratedNo?: string;
}

interface ImportReport {
  meta: {
    startedAt: string;
    finishedAt: string;
    file: string;
    dryRun: boolean;
    company: string;
  };
  summary: {
    total: number;
    success: number;
    skipped: number;
    failed: number;
    validationErrors: number;
  };
  rows: RowResult[];
}

function parseCliArgs(argv: string[]): CliArgs {
  const args: CliArgs = {
    file: null,
    company: 'XACH',
    dryRun: false,
    purgeTestData: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--file') {
      args.file = argv[i + 1] ?? null;
      i += 1;
    } else if (a === '--company') {
      args.company = argv[i + 1] ?? 'XACH';
      i += 1;
    } else if (a === '--dry-run') {
      args.dryRun = true;
    } else if (a === '--purge-test-data') {
      args.purgeTestData = true;
    }
  }
  return args;
}

function stripHeaderMarker(s: string): string {
  return s.endsWith('*') ? s.slice(0, -1) : s;
}

function normalizeHeaderMap(headerRow: string[]): Map<string, number> {
  const map = new Map<string, number>();
  headerRow.forEach((raw, idx) => {
    const name = stripHeaderMarker(String(raw ?? '').trim());
    if (name) map.set(name, idx);
  });
  return map;
}

function getCell(row: unknown[], idx: number): string {
  if (idx < 0 || idx >= row.length) return '';
  const v = row[idx];
  if (v === null || v === undefined) return '';
  if (typeof v === 'number') {
    return Number.isFinite(v) ? String(v) : '';
  }
  if (v instanceof Date) {
    const yyyy = v.getFullYear();
    const mm = String(v.getMonth() + 1).padStart(2, '0');
    const dd = String(v.getDate()).padStart(2, '0');
    return `${yyyy}-${mm}-${dd}`;
  }
  return String(v).trim();
}

function isValidDateString(s: string): boolean {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(s)) return false;
  const d = new Date(`${s}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return false;
  const [y, m, dd] = s.split('-').map(Number);
  return d.getUTCFullYear() === y && d.getUTCMonth() + 1 === m && d.getUTCDate() === dd;
}

function isValidPhone(s: string): boolean {
  return /^\d{11}$/.test(s);
}

function isValidIdCard(s: string): boolean {
  return /^\d{17}[\dX]$/i.test(s);
}

function isValidEmployeeNo(s: string): boolean {
  // 至少 6 位字母数字；不强格式，留给业务规则
  return /^[A-Za-z0-9]{4,30}$/.test(s);
}

function isValidDecimal(s: string): boolean {
  if (s === '') return false;
  const n = Number(s);
  return Number.isFinite(n) && n >= 0;
}

function toDecimalOrNull(s: string): number | null {
  if (s === '') return null;
  const n = Number(s);
  return Number.isFinite(n) ? n : null;
}

function toPercentOrNull(s: string): number | null {
  // 公积金比例(%)：Excel 填百分数（如 12）→ 存 0.12
  if (s === '') return null;
  const n = Number(s);
  if (!Number.isFinite(n) || n < 0 || n > 100) return null;
  return n / 100;
}

interface RawRow {
  rowIndex: number;
  values: Record<string, string>;
}

function readXlsx(filePath: string): { header: string[]; rows: RawRow[] } {
  // xlsx@0.18.5 ESM 命名空间下没有 readFile，需用 XLSX.read(Buffer, {type:'buffer'})
  const wb = XLSX.read(readFileSync(filePath), { type: 'buffer' });
  const firstName = wb.SheetNames[0];
  if (!firstName) throw new Error(`xlsx 无任何 sheet: ${filePath}`);
  const ws = wb.Sheets[firstName];
  const aoa = XLSX.utils.sheet_to_json<unknown[]>(ws, {
    header: 1,
    defval: '',
    raw: false,
    blankrows: false,
    dateNF: 'yyyy-mm-dd',
  });
  if (aoa.length < 1) throw new Error(`xlsx 表头为空: ${filePath}`);
  const header = (aoa[0] as unknown[]).map((h) => stripHeaderMarker(String(h ?? '').trim()));
  const headerMap = normalizeHeaderMap(header as string[]);

  for (const req of REQUIRED_HEADERS) {
    if (!headerMap.has(req)) {
      throw new Error(`xlsx 缺少必填列: ${req}。表头: ${header.join(' | ')}`);
    }
  }

  const dataRows = aoa.slice(1).map((rowArr, idx) => {
    const arr = rowArr as unknown[];
    const values: Record<string, string> = {};
    headerMap.forEach((colIdx, name) => {
      values[name] = getCell(arr, colIdx);
    });
    return { rowIndex: idx + 2, values };
  });
  return { header, rows: dataRows };
}

interface ValidationContext {
  deptCodeToId: Map<string, string>;
  existingEmpNos: Set<string>;
  fileDupes: Set<string>; // 文件内重复工号集合
}

async function buildValidationContext(companyCode: string): Promise<ValidationContext> {
  const company = await prisma.company.findFirst({
    where: { code: companyCode, deletedAt: null },
    select: { id: true },
  });
  if (!company) throw new Error(`公司不存在: ${companyCode}`);
  const depts = await prisma.department.findMany({
    where: { companyId: company.id, deletedAt: null },
    select: { id: true, code: true },
  });
  const deptCodeToId = new Map(depts.map((d) => [d.code, d.id]));
  const employees = await prisma.employee.findMany({
    where: { deletedAt: null },
    select: { employeeNo: true },
  });
  const existingEmpNos = new Set(employees.map((e) => e.employeeNo));
  return { deptCodeToId, existingEmpNos, fileDupes: new Set() };
}

function validateRow(
  raw: RawRow,
  ctx: ValidationContext,
): { input: CreateEmployeeInput | null; errors: CellError[]; willSkip: boolean } {
  const errors: CellError[] = [];
  const v = raw.values;

  // 必填
  const employeeNo = v['工号'] ?? '';
  const name = v['姓名'] ?? '';
  const deptCode = v['部门代码'] ?? '';
  const hireDateStr = v['入职日期'] ?? '';

  if (!employeeNo) errors.push({ field: '工号', reason: '必填缺失' });
  if (!name) errors.push({ field: '姓名', reason: '必填缺失' });
  if (!deptCode) errors.push({ field: '部门代码', reason: '必填缺失' });
  if (!hireDateStr) errors.push({ field: '入职日期', reason: '必填缺失' });

  if (employeeNo && !isValidEmployeeNo(employeeNo)) {
    errors.push({ field: '工号', reason: `格式非法: ${employeeNo}（4-30 位字母数字）` });
  }

  // 部门代码查库
  let departmentId: string | null = null;
  if (deptCode) {
    const id = ctx.deptCodeToId.get(deptCode);
    if (!id) errors.push({ field: '部门代码', reason: `不存在: ${deptCode}` });
    else departmentId = id;
  }

  // 日期
  if (hireDateStr && !isValidDateString(hireDateStr)) {
    errors.push({ field: '入职日期', reason: `日期非法: ${hireDateStr}（期望 YYYY-MM-DD）` });
  }

  // 性别
  let gender: string | undefined;
  if (v['性别']) {
    const mapped = ENUM_MAPS.gender[v['性别'] as keyof typeof ENUM_MAPS.gender];
    if (!mapped) errors.push({ field: '性别', reason: `枚举非法: ${v['性别']}（期望 男 / 女）` });
    else gender = mapped;
  }

  // 出生日期
  let birthDate: string | undefined;
  if (v['出生日期']) {
    if (!isValidDateString(v['出生日期'])) {
      errors.push({ field: '出生日期', reason: `日期非法: ${v['出生日期']}` });
    } else {
      birthDate = v['出生日期'];
    }
  }

  // 身份证
  if (v['身份证号'] && !isValidIdCard(v['身份证号'])) {
    errors.push({ field: '身份证号', reason: `格式非法: 期望 18 位（末位可为 X）` });
  }

  // 手机号
  if (v['手机号'] && !isValidPhone(v['手机号'])) {
    errors.push({ field: '手机号', reason: `格式非法: 期望 11 位数字` });
  }
  if (v['紧急联系人电话'] && !isValidPhone(v['紧急联系人电话'])) {
    errors.push({ field: '紧急联系人电话', reason: `格式非法: 期望 11 位数字` });
  }

  // 合同类型
  let contractType: string | undefined;
  if (v['合同类型']) {
    const mapped = ENUM_MAPS.contractType[v['合同类型'] as keyof typeof ENUM_MAPS.contractType];
    if (!mapped) errors.push({ field: '合同类型', reason: `枚举非法: ${v['合同类型']}（期望 正式 / 实习 / 顾问 / 劳务）` });
    else contractType = mapped;
  }

  // 合同日期
  let contractStart: string | undefined;
  if (v['合同开始日期']) {
    if (!isValidDateString(v['合同开始日期'])) errors.push({ field: '合同开始日期', reason: `日期非法: ${v['合同开始日期']}` });
    else contractStart = v['合同开始日期'];
  }
  let contractEnd: string | undefined;
  if (v['合同结束日期']) {
    if (!isValidDateString(v['合同结束日期'])) errors.push({ field: '合同结束日期', reason: `日期非法: ${v['合同结束日期']}` });
    else contractEnd = v['合同结束日期'];
  }

  // 参加社保
  let socialInsured: boolean | undefined;
  if (v['参加社保']) {
    const mapped = ENUM_MAPS.socialInsured[v['参加社保'] as keyof typeof ENUM_MAPS.socialInsured];
    if (mapped === undefined) errors.push({ field: '参加社保', reason: `枚举非法: ${v['参加社保']}（期望 是 / 否）` });
    else socialInsured = mapped;
  }

  // 状态
  let status: string | undefined;
  if (v['状态']) {
    const mapped = ENUM_MAPS.status[v['状态'] as keyof typeof ENUM_MAPS.status];
    if (!mapped) errors.push({ field: '状态', reason: `枚举非法: ${v['状态']}（期望 试用期 / 在职）` });
    else status = mapped;
  }

  // 数值
  let socialBase: number | undefined;
  if (v['社保基数']) {
    const n = toDecimalOrNull(v['社保基数']);
    if (n === null) errors.push({ field: '社保基数', reason: `数值非法: ${v['社保基数']}` });
    else socialBase = n;
  }
  let housingFundRate: number | undefined;
  if (v['公积金比例(%)']) {
    const n = toPercentOrNull(v['公积金比例(%)']);
    if (n === null) errors.push({ field: '公积金比例(%)', reason: `数值非法: ${v['公积金比例(%)']}（期望 0-100 的百分数）` });
    else housingFundRate = n;
  }
  let housingFundBase: number | undefined;
  if (v['公积金基数']) {
    const n = toDecimalOrNull(v['公积金基数']);
    if (n === null) errors.push({ field: '公积金基数', reason: `数值非法: ${v['公积金基数']}` });
    else housingFundBase = n;
  }
  let baseSalary: number | undefined;
  if (v['基本工资']) {
    if (!isValidDecimal(v['基本工资'])) errors.push({ field: '基本工资', reason: `数值非法: ${v['基本工资']}` });
    else baseSalary = Number(v['基本工资']);
  }
  let performanceSalary: number | undefined;
  if (v['绩效工资']) {
    if (!isValidDecimal(v['绩效工资'])) errors.push({ field: '绩效工资', reason: `数值非法: ${v['绩效工资']}` });
    else performanceSalary = Number(v['绩效工资']);
  }

  // 文件内重复 + 已存在
  let willSkip = false;
  if (employeeNo) {
    if (ctx.existingEmpNos.has(employeeNo)) {
      willSkip = true; // 库中已有 → 跳过（不算错误）
    } else if (ctx.fileDupes.has(employeeNo)) {
      errors.push({ field: '工号', reason: `文件内重复: ${employeeNo}` });
    } else {
      ctx.fileDupes.add(employeeNo);
    }
  }

  if (errors.length > 0) {
    return { input: null, errors, willSkip: false };
  }

  // 解析剩余字段（无校验失败的输入）
  const input: CreateEmployeeInput = {
    companyId: '', // 由 company code → id 解析后注入
    departmentId: departmentId!,
    name,
    hireDate: hireDateStr,
    gender,
    birthDate,
    idCard: v['身份证号'] || undefined,
    nativePlace: v['籍贯'] || undefined,
    ethnicity: v['民族'] || undefined,
    politicalStatus: v['政治面貌'] || undefined,
    phone: v['手机号'] || undefined,
    email: v['邮箱'] || undefined,
    emergencyContactName: v['紧急联系人'] || undefined,
    emergencyContactPhone: v['紧急联系人电话'] || undefined,
    address: v['家庭住址'] || undefined,
    educationLevel: v['学历'] || undefined,
    degree: v['学位'] || undefined,
    school: v['毕业院校'] || undefined,
    major: v['专业'] || undefined,
    graduationDate: v['毕业日期'] || undefined,
    contractType,
    contractStart,
    contractEnd,
    bankName: v['开户银行'] || undefined,
    bankCard: v['银行卡号'] || undefined,
    socialInsured,
    socialCity: v['社保城市'] || undefined,
    socialBase,
    housingFundCity: v['公积金城市'] || undefined,
    housingFundRate,
    housingFundBase,
    status: status ?? 'active',
    remark: v['备注'] || undefined,
    position: v['入职岗位'] || undefined,
    baseSalary,
    performanceSalary,
  };

  return { input, errors: [], willSkip };
}

async function getCompanyId(companyCode: string): Promise<string> {
  const c = await prisma.company.findFirst({
    where: { code: companyCode, deletedAt: null },
    select: { id: true },
  });
  if (!c) throw new Error(`公司不存在: ${companyCode}`);
  return c.id;
}

/**
 * 硬删除补偿：删除 employee_position_history + employee_salary_history + employees
 * 用于 createEmployee 成功但后续 update employeeNo 失败时的回滚
 */
async function hardDeleteEmployee(empId: string): Promise<void> {
  await prisma.$transaction([
    prisma.employeePositionHistory.deleteMany({ where: { employeeId: empId } }),
    prisma.employeeSalaryHistory.deleteMany({ where: { employeeId: empId } }),
    prisma.employee.delete({ where: { id: empId } }),
  ]);
}

async function importOne(
  input: CreateEmployeeInput,
  desiredEmployeeNo: string,
  name: string,
  rowIndex: number,
): Promise<RowResult> {
  try {
    const created = await createEmployee(input);
    const employeeId = (created as { id?: string }).id;
    const autoNo = (created as { employeeNo?: string }).employeeNo ?? '';
    if (!employeeId) {
      return {
        rowIndex,
        employeeNo: desiredEmployeeNo,
        name,
        result: 'failed',
        reason: 'createEmployee 返回数据缺少 id',
        autoGeneratedNo: autoNo,
      };
    }

    if (autoNo !== desiredEmployeeNo) {
      // 回写工号到 Excel 期望值
      try {
        await prisma.employee.update({
          where: { id: employeeId },
          data: { employeeNo: desiredEmployeeNo },
        });
      } catch (err) {
        // 唯一约束冲突（P2002）等 → 补偿回滚（硬删除刚建的记录）
        const code = err instanceof Prisma.PrismaClientKnownRequestError ? err.code : 'unknown';
        try {
          await hardDeleteEmployee(employeeId);
        } catch (rollbackErr) {
          return {
            rowIndex,
            employeeNo: desiredEmployeeNo,
            name,
            result: 'failed',
            reason: `工号回写失败(${code}) 且补偿回滚失败: ${rollbackErr instanceof Error ? rollbackErr.message : rollbackErr}`,
          };
        }
        return {
          rowIndex,
          employeeNo: desiredEmployeeNo,
          name,
          result: 'failed',
          reason: `工号回写失败(${code})：已存在的工号 ${desiredEmployeeNo}；该行已被回滚`,
        };
      }
    }

    return {
      rowIndex,
      employeeNo: desiredEmployeeNo,
      name,
      result: 'success',
      employeeId,
      autoGeneratedNo: autoNo,
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return {
      rowIndex,
      employeeNo: desiredEmployeeNo,
      name,
      result: 'failed',
      reason: `createEmployee 异常: ${msg}`,
    };
  }
}

async function purgeTestData(): Promise<number> {
  // 仅删除 XACH2099 前缀的测试数据。子表无 FK（employeePositionHistory / employeeSalaryHistory），
  // 但仍走 prisma.$transaction 保证三表同步删除，避免遗留孤儿。
  const ids = await prisma.employee.findMany({
    where: { employeeNo: { startsWith: TEST_EMP_PREFIX } },
    select: { id: true },
  });
  if (ids.length === 0) {
    console.log(`未找到 ${TEST_EMP_PREFIX} 前缀员工，无需清理`);
    return 0;
  }
  const idList = ids.map((x) => x.id);
  await prisma.$transaction([
    prisma.employeePositionHistory.deleteMany({ where: { employeeId: { in: idList } } }),
    prisma.employeeSalaryHistory.deleteMany({ where: { employeeId: { in: idList } } }),
    prisma.employee.deleteMany({ where: { id: { in: idList } } }),
  ]);
  return ids.length;
}

async function main(): Promise<void> {
  const args = parseCliArgs(process.argv.slice(2));

  if (args.purgeTestData) {
    const n = await purgeTestData();
    console.log(`✓ purge 完成，删除 ${n} 行 ${TEST_EMP_PREFIX} 前缀员工`);
    await prisma.$disconnect();
    process.exit(0);
  }

  if (!args.file) {
    console.error('缺少 --file 参数');
    console.error('用法: pnpm --filter hrms-server migration:employees -- --file <xlsx> [--dry-run] [--company XACH] [--purge-test-data]');
    process.exit(2);
  }

  const filePath = path.isAbsolute(args.file)
    ? args.file
    : path.join(SCRIPT_DIR, args.file);
  console.log(`▶ 开始 ${args.dryRun ? 'dry-run' : '正式导入'}: ${filePath}`);

  const { rows } = readXlsx(filePath);
  console.log(`  解析到 ${rows.length} 行数据`);

  const ctx = await buildValidationContext(args.company);
  console.log(`  公司: ${args.company}（部门 ${ctx.deptCodeToId.size} 个 / 既有员工 ${ctx.existingEmpNos.size} 名）`);

  const companyId = await getCompanyId(args.company);

  const startedAt = new Date();
  const rowResults: RowResult[] = [];
  let validationErrorCount = 0;

  // 阶段 1：校验所有行
  const validated: Array<{ raw: RawRow; input: CreateEmployeeInput | null; errors: CellError[]; willSkip: boolean }>
    = [];
  for (const raw of rows) {
    const result = validateRow(raw, ctx);
    validated.push({ raw, ...result });
    if (result.errors.length > 0) validationErrorCount += 1;
  }

  if (validationErrorCount > 0) {
    console.log(`\n✗ 校验发现 ${validationErrorCount} 行错误，整个文件不入库`);
    for (const v of validated) {
      if (v.errors.length > 0) {
        const errText = v.errors.map((e) => `[${e.field}] ${e.reason}`).join('; ');
        rowResults.push({
          rowIndex: v.raw.rowIndex,
          employeeNo: v.raw.values['工号'] || '',
          name: v.raw.values['姓名'] || '',
          result: 'failed',
          reason: errText,
          errors: v.errors,
        });
        console.log(`  行 ${v.raw.rowIndex}: ${errText}`);
      } else if (v.willSkip) {
        // 即使本文件有错误，也顺手列出「将跳过」行（让用户看全每行反馈）
        rowResults.push({
          rowIndex: v.raw.rowIndex,
          employeeNo: v.raw.values['工号'] || '',
          name: v.raw.values['姓名'] || '',
          result: 'skipped',
          reason: '工号已存在于数据库，将跳过（但本文件整体不入库）',
        });
      }
    }
    const finishedAt = new Date();
    const report: ImportReport = {
      meta: {
        startedAt: startedAt.toISOString(),
        finishedAt: finishedAt.toISOString(),
        file: filePath,
        dryRun: args.dryRun,
        company: args.company,
      },
      summary: {
        total: rows.length,
        success: 0,
        skipped: rowResults.filter((r) => r.result === 'skipped').length,
        failed: rowResults.filter((r) => r.result === 'failed').length,
        validationErrors: validationErrorCount,
      },
      rows: rowResults,
    };
    writeReport(report);
    await prisma.$disconnect();
    process.exit(1);
  }

  // dry-run 报告（不写库）
  if (args.dryRun) {
    let willSkipCount = 0;
    let willImportCount = 0;
    for (const v of validated) {
      if (v.willSkip) {
        willSkipCount += 1;
        rowResults.push({
          rowIndex: v.raw.rowIndex,
          employeeNo: v.raw.values['工号'],
          name: v.raw.values['姓名'],
          result: 'skipped',
          reason: '工号已存在于数据库，dry-run 不重复导入',
        });
        console.log(`  [skip] 行 ${v.raw.rowIndex}: ${v.raw.values['工号']} ${v.raw.values['姓名']}`);
      } else {
        willImportCount += 1;
        rowResults.push({
          rowIndex: v.raw.rowIndex,
          employeeNo: v.raw.values['工号'],
          name: v.raw.values['姓名'],
          result: 'success', // dry-run 阶段标 success 表示预期成功
          reason: 'dry-run 预演：未实际写入',
        });
        console.log(`  [ok]   行 ${v.raw.rowIndex}: ${v.raw.values['工号']} ${v.raw.values['姓名']}`);
      }
    }
    console.log(`\n✓ dry-run 完成：合法 ${willImportCount} / 将跳过 ${willSkipCount} / 失败 0`);
    const finishedAt = new Date();
    const report: ImportReport = {
      meta: {
        startedAt: startedAt.toISOString(),
        finishedAt: finishedAt.toISOString(),
        file: filePath,
        dryRun: true,
        company: args.company,
      },
      summary: {
        total: rows.length,
        success: willImportCount,
        skipped: willSkipCount,
        failed: 0,
        validationErrors: 0,
      },
      rows: rowResults,
    };
    writeReport(report);
    await prisma.$disconnect();
    process.exit(0);
  }

  // 阶段 2：正式导入
  let successCount = 0;
  let skippedCount = 0;
  let failedCount = 0;
  for (const v of validated) {
    if (v.willSkip) {
      skippedCount += 1;
      const r: RowResult = {
        rowIndex: v.raw.rowIndex,
        employeeNo: v.raw.values['工号'],
        name: v.raw.values['姓名'],
        result: 'skipped',
        reason: '工号已存在于数据库，跳过（幂等）',
      };
      rowResults.push(r);
      console.log(`  [skip] 行 ${v.raw.rowIndex}: ${r.employeeNo} ${r.name}`);
    } else {
      const input: CreateEmployeeInput = { ...v.input!, companyId };
      const r = await importOne(
        input,
        v.raw.values['工号'],
        v.raw.values['姓名'],
        v.raw.rowIndex,
      );
      if (r.result === 'success') successCount += 1;
      else failedCount += 1;
      rowResults.push(r);
      const tag = r.result === 'success' ? '[ok]  ' : '[fail]';
      console.log(`  ${tag} 行 ${v.raw.rowIndex}: ${r.employeeNo} ${r.name}${r.reason ? ` — ${r.reason}` : ''}`);
    }
  }

  const finishedAt = new Date();
  console.log(`\n✓ 导入完成：成功 ${successCount} / 跳过 ${skippedCount} / 失败 ${failedCount}`);

  const report: ImportReport = {
    meta: {
      startedAt: startedAt.toISOString(),
      finishedAt: finishedAt.toISOString(),
      file: filePath,
      dryRun: false,
      company: args.company,
    },
    summary: {
      total: rows.length,
      success: successCount,
      skipped: skippedCount,
      failed: failedCount,
      validationErrors: 0,
    },
    rows: rowResults,
  };
  writeReport(report);

  await prisma.$disconnect();
  process.exit(failedCount > 0 ? 1 : 0);
}

function writeReport(report: ImportReport): void {
  mkdirSync(OUTPUT_DIR, { recursive: true });
  const now = new Date();
  const pad = (n: number) => String(n).padStart(2, '0');
  const stamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
  const file = path.join(OUTPUT_DIR, `import-report-${stamp}.json`);
  writeFileSync(file, JSON.stringify(report, null, 2), 'utf8');
  console.log(`\n📄 报告已落盘: ${path.relative(SCRIPT_DIR, file)}`);
}

main().catch((err) => {
  console.error('迁移脚本异常:', err);
  process.exit(2);
});
